version: '2'
services:
  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec rails s -b '0.0.0.0'
    volumes:
      - .:/pelada-tech
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  postgres-data:
